version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  # Maintain dependencies for pip
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    # Disable version updates for docker dependencies until
    # PR 63 has been debugged and fixed
    # https://github.com/sgibson91/bump-jhub-image-action/pull/63
    open-pull-requests-limit: 0
