name: CI Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  python-lint-format:
    uses:
      sgibson91/.github/.github/workflows/python-lint-format.yaml@main

  run-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package requirements
        run: |
          python -m pip install -r requirements.txt

      - name: Install dev requirements
        run: |
          python -m pip install -r dev-requirements.txt

      - name: Run test suite
        run: |
          python -m coverage run -m pytest -vvv

      - name: Print coverage report
        run: |
          python -m coverage report

  check-static-typing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dev requirements
        run: |
          python -m pip install -r dev-requirements.txt

      - name: Run mypy static checker
        run: |
          mypy tag_bot/
