name: Test Building Docker Image

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  docker-build-pr:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Test Docker Build
        uses: docker/build-push-action@v3.0.0
        with:
          push: false
          tags: ${{ github.repository }}:${{ github.head_ref }}

  docker-build-push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment: docker
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Image
        uses: docker/build-push-action@v3.0.0
        with:
          push: true
          tags: ${{ github.repository }}:${{ github.ref_name }}
