name: Build and Push Docker Image

on:
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - "main"

jobs:
  docker-build-push:
    uses:
      sgibson91/.github/.github/workflows/docker-build.yaml
